name: Build React App
run-name: ${{ github.actor }} updated the build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run build
      - env:
          GIT_USER: github-actions
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${GIT_USER}"
          git config --global user.email "github-actions@users.noreply.github.com"
          npm run deploy
